name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Functions Dependencies
        run: npm --prefix functions install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          action: deploy
          project_id: 'team-nethra'
          token: ${{ secrets.FIREBASE_TOKEN }}
          args: --only functions
        env:
          BREVO_KEY: ${{ secrets.BREVO_KEY }}
