name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Functions Dependencies
        # Use 'npm ci' for a clean, reliable install in CI environments
        run: npm --prefix functions ci

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          # We pass all commands in the 'args' input now
          args: deploy --only functions --project team-nethra
        env:
          # The Firebase token is now passed as an environment variable
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          # The Brevo key is also passed as an environment variable
          BREVO_KEY: ${{ secrets.BREVO_KEY }}
